version: "2"
services:
  jenkins:
    image: my-jenkins:1.651.2
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:8080"
    tty: true
    restart: always
